name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    uses: anvaplus/homelab-github-workflows/.github/workflows/Hugo_PullRequest.yaml@main
    with:
      sonar_organization: ${{ vars.SONAR_ORGANIZATION }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
